### ISSUE TITLE
Could you please upgrade project to use Spring Boot version 2.1.1.RELEASE?

### ISSUE THREAD

**Issue by JavaHelper** [piomin/sample-spring-microservices-new#13]

**Comment by piomin** [comment]
You should upgrade Spirng Boot without upgrading Spring Cloud version. It is not recommended.

**Comment by JavaHelper** [comment]
I upgrade Spring Boot version 2.1.2.RELEASE and spring cloud dependencies version to Greenwich.RC2. It looks like the discovery-service is not starting properly & giving the errors. Thus none of the other services are starting correctly.

Would you want to take a look at ?
