### ISSUE TITLE
Is this correct that both gateway-service.yml and proxy-service.yml using same port 8060 ?

### ISSUE THREAD

**Issue by JavaHelper** [piomin/sample-spring-microservices-new#14]
Is this correct that both gateway-service.yml and proxy-service.yml using same port 8060 ?

**Comment by GuiF007** [comment]
Yes, because proxy-service is an alternative API gateway based on Netflix Zuul to gateway-service based on Spring Cloud Gateway.

**Comment by Biggo6** [comment]
I got this error

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8060 was already in use.

Action:

Identify and stop the process that's listening on port 8060 or configure this application to listen on another port.

**Comment by GuiF007** [comment]
Start only ONE of between gateway-service and proxy-service...

**Comment by GuiF007** [comment]
@Biggo6 Yeap you're right, because gateway-service is not compatible with...

**Comment by piomin** [comment]
Ok, I'm closing this issue. You can always change the port, but running two gateways which ale an alternative does not really have sense.
