### ISSUE TITLE
No plugin found for prefix 'jib' in the current project !

### ISSUE THREAD

**Issue by mehdi-salehi** [piomin/sample-spring-microservices-new#65]
C:\Users\MsM\Desktop\sample-spring-microservices-new-master>  mvn clean package -Pbuild-image jib:dockerBuild
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] sample-spring-microservices-new                                    [pom]
[INFO] discovery-service                                                  [jar]
[INFO] config-service                                                     [jar]
[INFO] employee-service                                                   [jar]
[INFO] department-service                                                 [jar]
[INFO] organization-service                                               [jar]
[INFO] gateway-service                                                    [jar]
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 12 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (21 kB at 12 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] sample-spring-microservices-new 1.1-SNAPSHOT ....... SKIPPED
[INFO] discovery-service 1.1-SNAPSHOT ..................... SKIPPED
[INFO] config-service 1.1-SNAPSHOT ........................ SKIPPED
[INFO] employee-service 1.2-SNAPSHOT ...................... SKIPPED
[INFO] department-service 1.2-SNAPSHOT .................... SKIPPED
[INFO] organization-service 1.2-SNAPSHOT .................. SKIPPED
[INFO] gateway-service 1.1-SNAPSHOT ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.729 s
[INFO] Finished at: 2023-07-01T11:39:47+03:30
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jib' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\MsM\.m2\repository), central (https://repo.mave
n.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by piomin** [comment]
Hi! You just need to run `mvn clean package -Pbuild-image` without jib:dockerBuild. The `build-image` profile activate jib plugin

**Comment by mehdi-salehi** [comment]
Thanks!
It's work NOW.
